### ISSUE TITLE
Allow users to configure the internal thread pool.

### ISSUE THREAD

**Issue by alxmrs** [google/Xee#11]
Let's add an optional dictionary kwarg to let users configure the internal `concurrent.futures.ThreadPool`.

**Comment by alhridoy** [comment]
Hi @alxmrs,
I've created a pull request that addresses issue #11. I added an optional dictionary argument to the _raw_indexing_method function to allow users to configure the internal concurrent.futures.ThreadPool.

**Comment by alhridoy** [comment]
Hi @alxmrs , I am sorry for the prior inconvenience. Can I work on it again? Now that, I got your feedback, and believe I can work on it. Thanks

**Comment by dabhicusp** [comment]
Hello @alhridoy I have an immediate use-case of configuring the internal thread pool so I take a reference of your PR & raised a new PR with all necessary changes. 
BTW thanks for the contribution 🎉 .
