### ISSUE TITLE
Output change for the same code

### ISSUE THREAD

**Issue by leonelqz** [google/Xee#160]
Hi,

I have this issue:

Two days ago, I ran the following lines of code
 ```
import xarray as xr
import ee

credentials = ee.ServiceAccountCredentials(service_account, json_path)
ee.Initialize(credentials)

ds = xr.open_dataset("ee://NOAA/CDR/OISST/V2_1", engine="ee", chunks="auto" )

# Get lon in degrees east
coords = [ lon % 360 for lon in ds.lon.values if lon < 0 ] + [lon for lon in ds.lon.values if lon >=0 ]
ds_360 = ds.assign_coords(lon=coords).sortby("lon")

hov = ds_360.anom.sel(lon=slice(160, 280), lat=slice(-5,5)).groupby("time").mean("lat")

hov.load()
```

And I got a DataArray with all values different from NaN, perfect! (I still have it in .nc file local, ~7mb)

But now, when I run the same lines of code, I get an array with all NaN values or this traceback: 
`ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

I would like to know what's wrong. I need the first output and don't understand why I didn't get it after that day.

Thanks!

**Comment by leonelqz** [comment]
seems the problem already has been resolved...  I am not sure if the first time, I used opt_url='https://earthengine-highvolume.googleapis.com' in Initialize...

**Comment by naschmitz** [comment]
Sounds like this has been fixed. Closing the issue. Thank you for reporting!
