### ISSUE TITLE
Publish the package on conda-forge

### ISSUE THREAD

**Issue by giswqs** [google/Xee#67]
I am trying to get xee published on conda-forge. However, the source distribution of the package is not available on PyPI. It would be great to include it. 

![image](https://github.com/google/Xee/assets/5016453/aa9fe160-0c9a-4b6b-aced-fab35ec89911)

**Comment by alxmrs** [comment]
That's strange! Do you have a link to that page? I'd like to read up on docs on generating source distributions. 

Thank you so much for offering to publish this on conda-forge!!

**Comment by giswqs** [comment]
Run `python setup.py sdist`. It should generate the sdist for for the package under the `dist` folder. Then use `twine upload dist/xee-0.0.0.tar.gz` to upload it to PyPI.

**Comment by alxmrs** [comment]
I'm not sure if this is related, but the Github Action I have to automate this hit a 500 error on the initial release: https://github.com/google/Xee/actions/runs/6474446174

**Comment by alxmrs** [comment]
Any ideas what could have caused this? This is the config: https://github.com/google/Xee/blob/085de84b860300b5b1f5dd8f7ce7e9faf9f4befc/.github/workflows/publish.yml#L81

**Comment by giswqs** [comment]
It seems a PyPI server timeout issue. Try rerun the failed task. It might fix it. 

https://github.com/google/Xee/actions/runs/6474446174/job/17579463823
![image](https://github.com/google/Xee/assets/5016453/9cbe16d8-9b83-4d48-9c8f-46718d6257b5)

**Comment by alxmrs** [comment]
Re-running it worked! Third time was the charm :)

**Comment by giswqs** [comment]
I have submitted the PR to add xee to conda-forge. We will see how it goes. 
https://github.com/conda-forge/staged-recipes/pull/24198
