### ISSUE TITLE
XEE does not return expected coordinate ranges/coordinates are offset

### ISSUE THREAD

**Issue by raspstephan** [google/Xee#71]
Thanks to #57 the returned coordinates are now correct. However, the coordinate ranges are not what would be expected. Take these two examples. 
<img width="802" alt="image" src="https://github.com/google/Xee/assets/2786927/7dfec38e-b27f-4acb-9619-c67c2770e479">
Which returns the following coordinates
<img width="713" alt="image" src="https://github.com/google/Xee/assets/2786927/ad3a7f5c-8ffb-4152-a89e-f261d459783e">

And

<img width="796" alt="image" src="https://github.com/google/Xee/assets/2786927/130eee56-1d4f-4ce8-835c-3904d1da3637">
which returns

<img width="711" alt="image" src="https://github.com/google/Xee/assets/2786927/893a4607-c8d9-4a1a-89d6-6d97ac8c1f5a">

(I think we can ignore the 0.07 difference in lat here, probably an EE rounding issue?)

First issues here:
1. In the first example, lat only goes back to 88.5 instead of 89.5 (which would be expected for a global geometry). 
2. In the second example. even though the geometry is the same in lat/lon, the shape is (11, 10). 

I believe this is due to https://github.com/google/Xee/blob/main/xee/ext.py#L239 which changes y_max. Removing the `+ self.scale_y` produces the expected output for the first example, i.e. lat = [89.5, ..., -89.5] and returns a (11, 11) shape for the second example with the following coordinates.
<img width="719" alt="image" src="https://github.com/google/Xee/assets/2786927/63cff950-3ee3-4cc6-8d49-387215ff5b77">
However, I am not sure exactly why this was added in the first place and don't know if this would fail in other cases.

Second issue is about the 0.5 offset with respect to the specified geometry:
1. In the first example with a bbox of (-180.0, -90.0, 180.0, 90.0), the array starts at -179.5 and 89.5.
2. In the second example with a bbox of (9.0, 10.0, 20.0, 20.070308685302734), the array starts at 9.5 and 19.5

I am wondering what the x_start and y_start parameters in https://github.com/google/Xee/blob/main/xee/ext.py#L422 should do. In my cases they are always zero. I played around with `self.scale_x * 0.5`, etc. but the issue is that the direction of the offset is different depending on whether the bbox is at the edge (e.g. -180) or not (e.g. 10). At the edge the offset is positive (-180 + 0.5 = -179.5) while in other cases it is negative (10 - 0.5 = 9.5). 

Note that I can "fix" the second case myself by specifying the following geometry: `ee.Geometry.Rectangle(10.5, 10, 20, 20.5)`. But this doesn't work for the global case.

Why is the offset there in the first place? Is there a way to specify in the grid that you'd actually want the values at the given grid points rather than in the middle?

Alternatively, one could write some logic that computes whether the offset should be negative or positive. 

PS: In the end, I would love to get an array that matches, e.g. the WB2 Zarr files starting at -180 and 90 (or-90).

**Comment by alxmrs** [comment]
This is related to #40. The adjustments to ranges in the implementation today are to handle a data discrepancy between raw `computePixels()` on patches and what is output from Xee. My "fix" for this issue seems to have made it worse. I'll revert for now since @saicheems is working on a much better fix to the original issue.

**Comment by raspstephan** [comment]
I am not sure this is fully fixed. 
<img width="971" alt="image" src="https://github.com/google/Xee/assets/2786927/58415429-481c-4041-9f09-f63cd129f696">
now returns 
<img width="725" alt="image" src="https://github.com/google/Xee/assets/2786927/b9dc3e80-4947-4f2a-b680-8d59fc2c0008">
which is different in the lon dimension by +1 but still gives a 10x11 shape even though the lat and lon ranges are the same.
