### ISSUE TITLE
export to local directly

### ISSUE THREAD

**Issue by kongdd** [google/Xee#73]
This tool is pretty awesome. But I have no `GCP`.
Just wondering whether is it possible to export data to local directly.

Thanks.

**Comment by alxmrs** [comment]
Hey Dongdong, 

You can use Xarray to write small bits of the data to a local file. For example, you can write data to netCDF with the following code: 
```
!pip install netcdf4
ds = xarray.open_dataset('ee://ECMWF/ERA5_LAND/HOURLY', engine='ee',
                         crs='EPSG:4326', scale=0.25)

halloween = ds.sel(time='2022-10-31')
# the scipy netCDF engine was broken when I last tested it
halloween.temperature_2m.to_netcdf('halloween-temp2m-2022.nc', engine='netcdf4')
```

As a general warning, it may take a long time to download, depending on how big the data in the `xarray.Dataset` is!

**Comment by kongdd** [comment]
It is bloody fast. Very cool!
One year data only costs about 1.5 mins.

It will be much better if there is a progress bar.

![image](https://github.com/google/Xee/assets/9815742/93ef2058-cd83-4b90-a023-9873631987a2)

**Comment by kongdd** [comment]
Thanks for your awesome Tool. It saves lots of time for me.

**Comment by kongdd** [comment]
This is my case. 
<https://github.com/kongdd/xee_abc/blob/master/gee-01.ipynb>

It could be another example about how to use xee locally.

**Comment by alxmrs** [comment]
For a local focused interface with things like a progress bar, consider https://github.com/aazuspan/wxee
