### ISSUE TITLE
upstream examples to gee docs

### ISSUE THREAD

**Issue by raybellwaves** [google/Xee#82]
It would be great if examples are upstreamed to the google earth docs.

For example, there is could be a new python tab in https://developers.google.com/earth-engine/guides/scale#code-editor-javascript using xee

Or there could be some integration with with the current python (geemap) examples https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC08_C02_T1_TOA#colab-python-sample

**Comment by jdbcode** [comment]
@raybellwaves thanks for the suggestions!

More examples are in our plans. At this point I don't think they'll be included in [https://developers.google.com/earth-engine](https://developers.google.com/earth-engine) pages. It will more likely be something independent like a [Read the Docs](https://docs.readthedocs.io/en/stable/) site.

**Comment by jdbcode** [comment]
Closing as "planned docs enhancement"
