### ISSUE TITLE
ee to_xarray() method

### ISSUE THREAD

**Issue by raybellwaves** [google/Xee#83]
I know it's outside the scope of this project and It wasn't obvious how to make a feature requeset to https://github.com/google/earthengine-api

I think a good long term goal would be to add a `.to_xarray()` method to ee objects e.g. `ee.Image('LANDSAT/LC08/C02/T1_TOA/LC08_044034_20140318').select('B4').to_xarray()` which I would imagine uses xee under the hood

**Comment by 12rambau** [comment]
I think on the other hand it's clearly in the scope of `geetools`. In the current refactoring of the lib (https://github.com/gee-community/gee_tools/tree/1.x) I'm integrating all the existing functionalities of gee_tools + some very nice extentions inside an extention "namespace". 

It would be `ee.image.constant(1).geetools.to_xarray()` do You think it would do the trick ?

**Comment by alxmrs** [comment]
I think it would be more appropriate to call `to_xarray()` on an image collection and not an image.

**Comment by 12rambau** [comment]
Sure you are very right (but considering the last example of the readme this option is also on the table 😀)

**Comment by 12rambau** [comment]
It should be released in geetools v1.1.0
