### ISSUE TITLE
 Pixel grid dimensions (40818x1) must be less than or equal to 32768.

### ISSUE THREAD

**Issue by simonff** [google/Xee#85]
Repro:

import ee
import xarray
import numpy as np

ee.Initialize()

geom = ee.Geometry.Rectangle([-61, -7, -50, -18])
county = ee.Feature(geom)
image = ee.Image('projects/mapbiomas-workspace/TRANSVERSAIS/ZONACOSTEIRA6/mosaic_1985').clip(county)
coll = ee.ImageCollection(image)
ds = xarray.open_dataset(
    coll.select(['NDVI']), crs='EPSG:3857', scale=30,geometry=geom,
    chunks={'time':1,'X': 512, 'Y': 512}, engine='ee')

**Comment by thomaslauber** [comment]
Same problem here. I think so far only images in collections can be downloaded. Would be nice to extent it to global images too.
