### ISSUE TITLE
Issue with default ee_mask_value with float32 datasets

### ISSUE THREAD

**Issue by spatialthoughts** [google/Xee#86]
XEE's `open_dataset()` method uses a default integer mask value as commented in the code below

```
      ee_mask_value (optional): Value to mask to EE nodata values. By default,
        this is 'np.iinfo(np.int32).max' i.e. 2147483647.
```

For image bands that are integer or float64 this works fine. But for float32 values this results in the nodata values having a large number `2.14748365e+09` causing all sort of problems. There are 2 workaround that fixes this. 

Workaround 1: Specify a custom nodata value in `open_dataset()` such as `ee_mask_value=-9999`

```
ds = xarray.open_dataset(
    withNdvi.select('ndvi'),
    engine='ee',
    crs='EPSG:3857',
    scale=10,
    geometry=geometry,
    ee_mask_value=-9999
)
```

Workaround 2: Cast the input bands to float64 using `toDouble()`

```
ndviCasted = withNdvi.select('ndvi').map(lambda img: img.toDouble())
ds = xarray.open_dataset(
    ndviCasted,
    engine='ee',
    crs='EPSG:3857',
    scale=10,
    geometry=geometry,
)
```

It would be good to fix this so the workaround is not required. Below is a notebook demonstrating the problem and the workaround.
https://colab.research.google.com/drive/1jDcgQ3LDsHxyvTmAmnqyXAGYLUgwRwAN?usp=sharing

**Comment by dabhicusp** [comment]
Hello @spatialthoughts Can you close this issue as PR #103 is merged which is resolved this issue.
