### ISSUE TITLE
Find an efficient way to convert a structured numpy array into a 3d array.

### ISSUE THREAD

**Issue by alxmrs** [google/Xee#9]
The current implementation is: 
```
arr = np.array(raw.tolist(), dtype=self.dtype)
```

I am pretty sure this is inefficient / incurs too much of a memory cost.

**Comment by KMarkert** [comment]
You may be able to use `arr = raw.view(self.dtype)`

Using `.view()` doesn't seem to change the data buffer and may be memory efficient than making a copy https://numpy.org/doc/stable/user/basics.copies.html#view

**Comment by alxmrs** [comment]
Thanks Kel! That seems like a really fruitful approach. :)
